version: '3.9'

services:
  web:
    build: .
    image: craftvalley
    ports:
      - "3000:3000"
    volumes:
      - ./craftvalley:/craftvalley
    working_dir: /craftvalley
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    command: ["python", "manage.py", "runserver", "0.0.0.0:3000"]

  migrate:
    build: .
    image: craftvalley
    volumes:
      - ./craftvalley:/craftvalley
    working_dir: /craftvalley
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "manage.py", "migrate"]

  db:
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cvdb
    ports:
      - "3307:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 60s
      retries: 5
      interval: 10s
